from chatterbot.adapters.output import Gitter


class SelectiveGitterResponse(Gitter):
    """
    Only return a response if a high confidence value is
    generated by the logic adapter.
    """

    def process_response(self, statement, confidence):
        # Only send a message if we are confident that a response should be sent
        if confidence > 0.5:
            self.send_message(statement.text)
        return statement